"use client"

import Link from "next/link"
import Image from "next/image"
import { ArrowRight, Truck, ShieldCheck, User, Headphones } from "lucide-react"
import ProductCard from "@/components/ui/ProductCard"
import Button from "@/components/ui/Button"
import { ProductGridSkeleton } from "@/components/ui/Skeleton"
import type { Category, Product } from "@/types"

interface Props { dbSections: any[]; categories: Category[]; featuredProducts: Product[]; newArrivals: Product[]; loading: boolean }

export default function HomepageRenderer({ dbSections, categories, featuredProducts, newArrivals, loading }: Props) {
  if (dbSections.length === 0) return null;
  return (<>
    {dbSections.map((s) => {
      switch (s.type) {
        case "HERO": return (<section key={s.id} className="container-shop relative mt-5 overflow-hidden rounded-[2rem] bg-[#1f2521] text-white shadow-[0_20px_70px_rgba(31,33,31,.18)] md:mt-7">{s.image && <div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:"url("+s.image+")"}} />}<div className="absolute -right-4 top-10 h-44 w-44 rounded-full bg-[#d5966e]/20 blur-3xl" /><div className="relative z-10 px-6 py-16 text-center"><p className="font-label mb-4 text-[9px] text-[#e0a681]">{s.subtitle||"Premium home, thoughtfully chosen"}</p><h1 className="font-display text-4xl sm:text-5xl md:text-6xl lg:text-7xl max-w-3xl mx-auto">{s.title||"Make space for living."}</h1>{s.description&&<p className="mt-5 max-w-lg mx-auto text-sm leading-7 text-white/80">{s.description}</p>}{s.buttonText&&<Link href={s.buttonLink||"/shop"} className="mt-8 inline-flex"><Button variant="accent" size="lg">{s.buttonText} <ArrowRight size={16} /></Button></Link>}</div></section>);
case "CATEGORIES": return (<section key={s.id} className="container-shop py-20 md:py-28"><div className="mb-8 flex items-end justify-between md:mb-12"><div><p className="font-label mb-3 text-[9px] text-accent">{s.subtitle||"Browse by mood"}</p><h2 className="font-display text-4xl md:text-5xl">{s.title||"Shop by Category"}</h2></div></div><div className="scrollbar-hide -mx-1 flex snap-x gap-4 overflow-x-auto px-1 pb-2 md:grid md:grid-cols-7 md:gap-4 md:overflow-visible">{categories.filter((x:any)=>(x.productCount||0)>0).map((cat)=>(<Link href={"/collections/"+cat.slug} key={cat.id} className="group min-w-[145px] snap-start md:min-w-0"><div className="relative aspect-[.82] overflow-hidden rounded-[1.35rem] bg-surface-muted">{cat.image?<Image src={cat.image} alt={cat.name} fill className="object-cover transition-transform duration-700 ease-out group-hover:scale-110" />:<div className="w-full h-full bg-[#f0ede8] flex items-center justify-center"><span className="text-[10px] font-medium text-[#b0aba6]">View</span></div>}<div className="absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-transparent" /><span className="absolute bottom-3 left-3 right-3 text-sm font-semibold text-white">{cat.name}</span></div></Link>))}</div></section>);
case "FEATURED_PRODUCTS": return (<section key={s.id} className="bg-surface-muted/65 py-20 md:py-28"><div className="container-shop"><div className="mb-8 flex items-end justify-between md:mb-12"><div><p className="font-label mb-3 text-[9px] text-accent">{s.subtitle||"Curated picks"}</p><h2 className="font-display text-4xl md:text-5xl">{s.title||"Selected for you."}</h2></div></div>{loading?<ProductGridSkeleton count={4} className="lg:grid-cols-4" />:featuredProducts.length===0?<div className="text-center py-12"><p className="text-text-muted text-sm">Discover our curated collection.</p></div>:<div className="stagger-in grid grid-cols-2 gap-4 md:gap-6 lg:grid-cols-4">{featuredProducts.slice(0,4).map((p,i)=><ProductCard key={p.id} product={p} priority={i<2} />)}</div>}</div></section>);
case "NEW_ARRIVALS": return (<section key={s.id} className="container-shop pb-20 md:pb-28"><div className="mb-8 flex items-end justify-between md:mb-12"><div><p className="font-label mb-3 text-[9px] text-accent">{s.subtitle||"Just arrived"}</p><h2 className="font-display text-4xl md:text-5xl">{s.title||"New in the home."}</h2></div></div>{loading?<ProductGridSkeleton count={3} />:<div className="stagger-in grid grid-cols-2 gap-4 md:grid-cols-3 md:gap-6">{newArrivals.slice(0,3).map((p,i)=><ProductCard key={p.id} product={p} priority={i===0} />)}</div>}</section>);
case "PROMOTIONAL_BANNER": return (<section key={s.id} className="container-shop py-10 md:py-16"><div className="relative overflow-hidden rounded-[2rem] bg-[#c9b8a6] px-7 py-16 md:px-16 md:py-20">{s.image&&<div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:"url("+s.image+")"}} />}<div className="relative z-10 text-center"><h2 className="font-display text-3xl md:text-5xl text-[#322923]">{s.title||"Special Offer"}</h2>{s.description&&<p className="mt-4 text-sm leading-7 text-[#4a3f38]">{s.description}</p>}{s.buttonText&&<Link href={s.buttonLink||"/shop"} className="mt-6 inline-flex"><Button variant="primary" size="md">{s.buttonText} <ArrowRight size={16} /></Button></Link>}</div></div></section>);
case "BRAND_STORY": return (<section key={s.id} className="bg-[#1f2521] py-20 text-white md:py-28"><div className="container-shop"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="font-label mb-4 text-[9px] text-[#e0a681]">{s.subtitle||"Why West Home"}</p><h2 className="font-display max-w-md text-4xl leading-[.95] md:text-6xl">{s.title||"Good design should feel easy."}</h2>{s.description&&<p className="mt-6 max-w-sm text-sm leading-7 text-white/65">{s.description}</p>}</div><div className="grid grid-cols-2 gap-x-5 gap-y-8 md:grid-cols-4 md:gap-8"><div><Truck size={21} className="mb-5 text-[#e0a681]" /><h3 className="text-sm font-semibold">Fast delivery</h3><p className="mt-2 text-xs leading-5 text-white/60">Pan-India delivery, 3-7 business days.</p></div><div><ShieldCheck size={21} className="mb-5 text-[#e0a681]" /><h3 className="text-sm font-semibold">Quality assured</h3><p className="mt-2 text-xs leading-5 text-white/60">Hand-picked materials, quality checked.</p></div><div><User size={21} className="mb-5 text-[#e0a681]" /><h3 className="text-sm font-semibold">Personal assistance</h3><p className="mt-2 text-xs leading-5 text-white/60">Real help when you need it.</p></div><div><Headphones size={21} className="mb-5 text-[#e0a681]" /><h3 className="text-sm font-semibold">Real support</h3><p className="mt-2 text-xs leading-5 text-white/60">We are here when you need us.</p></div></div></div></div></section>);
case "STORE_INFO": return (<section key={s.id} className="container-shop py-20 md:py-28"><div className="text-center"><p className="font-label mb-3 text-[9px] text-accent">{s.subtitle||"Visit us"}</p><h2 className="font-display text-4xl md:text-5xl">{s.title||"Visit Our Store"}</h2>{s.description&&<p className="mt-4 text-sm text-text-secondary max-w-md mx-auto">{s.description}</p>}{s.buttonText&&<Link href={s.buttonLink||"/contact"} className="mt-6 inline-flex"><Button variant="primary" size="md">{s.buttonText}</Button></Link>}</div></section>);
default: return null
}})}</>);
}
